// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyA5EcHZ-etRlyf0YFE-63-lE5uSvmbqNdA",
    appId: "1:41616583072:android:86fb3f19833d853eea9cc5",
    messagingSenderId: "41616583072",
    projectId: "nexnex-cfaf4",
    storageBucket: "nexnex-cfaf4.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvNyb6-XX54Tbycs9YlpqrTUqD8NRkai4',
    appId: '1:41616583072:ios:5f3209a1bd33d56dea9cc5',
    messagingSenderId: '41616583072',
    projectId: 'nexnex-cfaf4',
    storageBucket: 'nexnex-cfaf4.firebasestorage.app',
    androidClientId:
        '41616583072-nv73nk0ka2n3j5a8rs3jmqi37sqsi8lr.apps.googleusercontent.com',
    iosClientId:
        '41616583072-36ipbdq4dq2hbmltdirlfcttvtsromt6.apps.googleusercontent.com',
    iosBundleId: 'app.nexnex.com',
  );
}
